### ISSUE TITLE
[Bug]: Name missing for some channels - Showing only the Channel ID

### ISSUE THREAD

**Issue by TheDom42** [tubearchivist/tubearchivist-jf-plugin#12]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker - Jellyfin Official Container v10.9.1 - TubeArchivist Official container v0.4.7

## Describe the bug
Some of the channels (6 of 15 total) in the TubeArchivist library are only listed with their Channel ID as a name instead of their correct name. The channel still shows the correct channel picture, and the videos are listed with their correct name and thumbnail.

![image](https://github.com/tubearchivist/tubearchivist-jf-plugin/assets/26472356/ba423b57-01d9-4a86-8218-023a000bcb52)

The rest of the channels are fully correct with the right name and metadata.

## Steps To Reproduce
1. Set Up the plugin according to the Readme on the front page
2. Scan for Metadata

## Expected behavior
All Channels should show their correct name instead of their Channel ID as a name in Jellyfin.

### Relevant Jellyfin log output

```shell
######## Domain name substituted before posting for privacy reasons - Connection between containers works

[2024-05-17 00:00:19.346 +02:00] [INF] [19] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "https://example.com/api/channel/UC7aW7chIafJG6ECYAd3N5uQ/: OK"
[2024-05-17 00:00:19.346 +02:00] [INF] [19] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting metadata for channel: IBRACORP (UC7aW7chIafJG6ECYAd3N5uQ)"
[2024-05-17 00:00:19.346 +02:00] [INF] [19] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Received metadata: 
{\"channel_banner_url\":\"/cache/channels/UC7aW7chIafJG6ECYAd3N5uQ_banner.jpg\",\"channel_description\":\"Welcome to IBRACORP! \nWe share technology-related content in the hopes of helping or informing others in the art of information technology. \n\nWe also host our own servers and use our platform to expose open-source software to the world stage to help promote an open-source future. \n\nThe name is a play on the stereotype of generic greedy corporations - mysterious and very vague. A neon-Tokyo sort of future. \nIn our case, however, we want to share mostly free and open-source products. It also sounds cool, so there's that.\n\nThe motto is quoting a Dave Chappelle skit on Chappelle's Show - \\"Modern problems require modern solutions\\".\n\",\"channel_id\":\"UC7aW7chIafJG6ECYAd3N5uQ\",\"channel_name\":\"IBRACORP\",\"channel_tags\":null,\"channel_thumb_url\":\"/cache/channels/UC7aW7chIafJG6ECYAd3N5uQ_thumb.jpg\",\"channel_tvart_url\":\"/cache/channels/UC7aW7chIafJG6ECYAd3N5uQ_tvart.jpg\"}"
[2024-05-17 00:00:19.346 +02:00] [ERR] [19] MediaBrowser.Providers.TV.SeriesMetadataService: Error in "TubeArchivist"
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at Jellyfin.Plugin.TubeArchivistMetadata.TubeArchivist.Channel.ToSeries()
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by hugalafutro** [comment]
I was just watching logs and when it crashed during scan i restarted JF and pressed Scan all libraries, but perhaps there's more to it than that in your case. Also I noticed after restarting and pressing Scan it could take around 5 mins doing god knows what on all cpu cores and then it suddenly started scanning. 2 episodes dl'd yesterday appeared ok in JF by themselves later.

**Comment by jcaust** [comment]
I'm having the same issue. except I've got 300 folders to process and its only done 50. keep repeating scan and nothing extra is being added/processed .

**Comment by DarkFighterLuke** [comment]
Hi @TheDom42 , I haven't faced this bug on my small library, but I've also tried downloading a video from IBRACORP channel and metadata are retrieved without any problem.

About the time needed to scan, it depends on your library size, in my case it takes just 10 seconds with 64 videos.

@jcaust can you give me some examples of channels/videos not getting processed please?

Thanks

**Comment by hugalafutro** [comment]
@jcaust
consider setting the parallel scan to 1 as according to https://github.com/jellyfin/jellyfin/issues/11589#issuecomment-2108754230, my system is not that powerful + runs many apps + the media is going over gigabit nfs share - if you read more of the thread the 10.9.x release changed the logic there to run at more threads and it can cause issues in some of those circumstances.

For unrelated reasons I did rollback my container and re-import whole tube archivist library, and with the parallel setting at 1 it finished first time and imported all channels correctly.

see if that helps

NOTE: make sure you restart the jellyfin container/server after that. Also if it still bugs out, **just restarting the scan is not enough**, you have to restart the jf container/server and then restart the scan - once it stops its stuck until jf restart. Best way is monitoring logs for the SQLite db locked error at which point you know it's restart time. It's tedious/time consuming, but I successfully imported my whole t-a library both with the "broken" scan and successful scan with parallel setting at 1

**Comment by TheDom42** [comment]
> Hi @TheDom42 , I haven't faced this bug on my small library, but I've also tried downloading a video from IBRACORP channel and metadata are retrieved without any problem.

Unfortunately, I wouldn't know how to investigate further. What do you make of the error message I posted above? The `System.ArgumentNullException: Value cannot be null. (Parameter 'source')`
As I said, for most of my channels, there is no issue at all. The unrecognized ones aren't even the largest ones. I restarted/upgraded both containers multiple times. I also don't want to fully remove the library because I have already generated the trickplay files for it (which took quite some time), and I'm afraid I might lose them.

**Comment by DarkFighterLuke** [comment]
Can you try to setup another Jellyfin container and scan your Youtube library from there? So that we can exclude issues related to Jellyfin itself. (Please note: the Jellyfin configuration folder must be a different one from your current installation, we want a new clear instance)

**Comment by QuAzI** [comment]
In my case, no one video has a normal name. Also, if I switch on "Group to collections" - collections also looks like alphanumerical spaghetti.
Currently looks like I have to refetch all videos in TubeArchivist with option "**Embed metadata**" and then switch on in Jellyfin "**Prefer embedded titles over filenames**". In this way this plugin useless and superfluous

Jellyfin 10.9.11
TubeArchivist v0.4.10
TubeArchivistMetadata 1.3.2.0

![jf library settings](https://github.com/user-attachments/assets/6662504b-0c4a-490c-b508-f06745e5015a)

**Comment by hugalafutro** [comment]
All the issues disappeared for with few JF updates some time after this issue was posted, plugin now works as expected, pulls all metadata, videos and channels included, videos are named correctly and have correct thumbnails. Iirc I deleted and re added all t-a files after one update, maybe that helped, but now "it just works".

![Screenshot_2024-10-23-08-15-08-36_4b95a63cd60fd3e0f30739d89812bf6c](https://github.com/user-attachments/assets/215f75b6-f77c-4ff4-81e8-38df81d392c6)
![Screenshot_2024-10-23-08-15-35-60_4b95a63cd60fd3e0f30739d89812bf6c](https://github.com/user-attachments/assets/a9616279-9573-43bd-8e61-c7c49ebf3ada)

**Comment by QuAzI** [comment]
@hugalafutro 
Does your video files contain embedded metadata or all metadata including channels fetched by plugin?

**Comment by hugalafutro** [comment]
@QuAzI afaik I only have enabled embed thumbnails in t-a and rest just happens automatically. I literally only installed the plugin, added my t-a server and api key, created new library pointed at t-a data directory and got what's on the screenshots. The videos on 2nd screenshot were all pulled and added automatically without any intervention from me.

**Comment by QuAzI** [comment]
A new server will not help me as I have the latest versions in docker environment installed recently. So it doesn't work without some unobvious magic tricks

**Comment by DarkFighterLuke** [comment]
@QuAzI you are not required to embed metadata in media files, the plugin doesn't parse them, it makes only API requests to TA to fetch the information about each channel/media.
Please attach the Jellyfin logs for the scan.

**Comment by QuAzI** [comment]
Jellyfin logs in attachment.
I re-created "Youtube" collection again and it filled again with ids
[jellyfin.log.zip](https://github.com/user-attachments/files/17492448/jellyfin.log.zip)

Also, I am a bit confused with tasks duplication
![image](https://github.com/user-attachments/assets/d1a87b37-5f36-4873-87e3-c01a5098e765)

While I see no special task to sync metadata from TA

**Comment by QuAzI** [comment]
More logs if required. I still have no idea at which moment TA sync metadata. Looks like never
[jellyfin-20241024.log.zip](https://github.com/user-attachments/files/17501361/jellyfin-20241024.log.zip)

**Comment by AgentK20** [comment]
I've just fixed this in my fork @QuAzI. Feel free to follow the "Building" instructions to build from my fork and install the modified copy while we wait for the PR to get merged and a new version to get released.

**Comment by hugalafutro** [comment]
@AgentK20 hi, any chance you could upload the built .dll somewhere in the interim? I installed .NET 8, but unable to build on my win11 machine, do I need anything else? I'm only used to make not this win stuff. This is the error I get:
```
Administrator in tubearchivist-jf-plugin on  master via .NET v8.0.404
❯ dotnet publish Jellyfin.Plugin.TubeArchivistMetadata --configuration Release --output bin
  Determining projects to restore...
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'Jellyfin.Controller (>= 10.10.0)' for 'net8.0'.
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'Jellyfin.Model (>= 10.10.0)' for 'net8.0'.
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'Newtonsoft.Json (>= 13.0.3)' for 'net8.0'.
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'SerilogAnalyzer (>= 0.15.0)' for 'net8.0'.
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'StyleCop.Analyzers (>= 1.2.0-beta.507)' for 'net8.0'.
C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArchivistMetadata.cspro
j : error NU1100: Unable to resolve 'SmartAnalyzers.MultithreadingAnalyzer (>= 1.1.31)' for 'net8.0'.
  Failed to restore C:\Users\sammael\temp\tubearchivist-jf-plugin\Jellyfin.Plugin.TubeArchivistMetadata\Jellyfin.Plugin.TubeArc
  hivistMetadata.csproj (in 66 ms).
```
