### ISSUE TITLE
[Bug]: Jellyfin is not receiving any metadata from TubeArchivist

### ISSUE THREAD

**Issue by BobHassok** [tubearchivist/tubearchivist-jf-plugin#16]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker

## Describe the bug
Jellyfin is receiving no metadata from TubeArchivist. I have Jellyfin 10.9.7 and TubeArchivist 0.4.8 and tubearchivist-jf-plugin 1.3.0

## Steps To Reproduce
Follow the setup guide on this plug-in's github page

## Expected behavior
Jellyfin would receive metadata from TubeArchivist.

### Relevant Jellyfin log output

```shell
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[01:08:47] [ERR] [13] MediaBrowser.Providers.TV.SeriesMetadataService: Error in TubeArchivist
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[01:08:47] [ERR] [24] MediaBrowser.Providers.TV.SeriesMetadataService: Error in TubeArchivist
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[01:08:47] [ERR] [26] MediaBrowser.Providers.TV.SeriesMetadataService: Error in TubeArchivist
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.PersonInfo.set_Type(System.String)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by kidwellj** [comment]
Same issue for me. I'm using plugin 1.30.0, errors are:

```
[2024-07-04 21:20:06.188 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/H35dC2jLszY/: Forbidden"
[2024-07-04 21:20:06.188 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting images for video:  (H35dC2jLszY)"
[2024-07-04 21:20:06.188 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Thumb URI: "
[2024-07-04 21:20:06.195 +01:00] [INF] [77] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/youtube/UCVtz3s3FUxVxBgPl2OWtIJQ/gkoqN8QiuwY.mp4\" -threads 8 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-07-04 21:20:06.311 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/gkoqN8QiuwY/: Forbidden"
[2024-07-04 21:20:06.311 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting metadata for video:  (gkoqN8QiuwY)"
[2024-07-04 21:20:06.311 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Received metadata: 
null"
[2024-07-04 21:20:06.314 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/gkoqN8QiuwY/: Forbidden"
[2024-07-04 21:20:06.314 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting images for video:  (gkoqN8QiuwY)"
[2024-07-04 21:20:06.314 +01:00] [INF] [64] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Thumb URI: "
[2024-07-04 21:20:06.321 +01:00] [INF] [64] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/youtube/UCVtz3s3FUxVxBgPl2OWtIJQ/ZxNXA7QwcnM.mp4\" -threads 8 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-07-04 21:20:06.431 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/ZxNXA7QwcnM/: Forbidden"
[2024-07-04 21:20:06.432 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting metadata for video:  (ZxNXA7QwcnM)"
[2024-07-04 21:20:06.432 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Received metadata: 
null"
[2024-07-04 21:20:06.434 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/ZxNXA7QwcnM/: Forbidden"
[2024-07-04 21:20:06.434 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting images for video:  (ZxNXA7QwcnM)"
[2024-07-04 21:20:06.434 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Thumb URI: "
[2024-07-04 21:20:06.447 +01:00] [INF] [77] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/youtube/UCVtz3s3FUxVxBgPl2OWtIJQ/YiiHhT7NdGk.mp4\" -threads 8 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-07-04 21:20:06.535 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "http://192.168.1.208:8005/api/video/YiiHhT7NdGk/: Forbidden"
[2024-07-04 21:20:06.536 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Getting metadata for video:  (YiiHhT7NdGk)"
[2024-07-04 21:20:06.536 +01:00] [INF] [77] Jellyfin.Plugin.TubeArchivistMetadata.Plugin: "Received metadata: 
null"
```

**Comment by KoendeHaas** [comment]
Same issue here. 
- Jellyfin 10.9.7 
- TubeArchivist plugin 1.3.0.0
- TubeArchivist 0.4.8

Jellyfin is giving the follwing error:

```
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: https://local.tubearchivist.com/api/video/fyqe5csPLRA/: Forbidden
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Getting metadata for video:  (fyqe5csPLRA)
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Received metadata: null
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: https://local.tubearchivist.com/api/video/fyqe5csPLRA/: Forbidden
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Getting images for video:  (fyqe5csPLRA)
Jellyfin.Plugin.TubeArchivistMetadata.Plugin: Thumb URI: 
```
TubeArchivist output:
```
[pid: 55|app: 0|req: 630/630] 172.0.0.2 () {46 vars in 702 bytes} [Thu Jul 11 17:39:03 2024] GET /api/video/fyqe5csPLRA/ => generated 59 bytes in 7 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
[pid: 55|app: 0|req: 631/631] 172.0.0.2 () {46 vars in 702 bytes} [Thu Jul 11 17:39:03 2024] GET /api/video/fyqe5csPLRA/ => generated 59 bytes in 6 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
```

**Comment by aaroncoffey** [comment]
@kidwellj Turn on django debugging and you'll probably see that it's probably getting rejected because you are using the wrong host. Do you have `192.168.1.208` set as your host in the docker compose conf, or env var?

Same for @KoendeHaas but for `local.tubearchivist.com`

**Comment by KoendeHaas** [comment]
I have not changed a single thing to my setup since the inital report, but it appears to be suddenly working flawlessly for me. Not sure what the issue was, but it seems like a system reboot and some time has fixed it. Thanks for your help @aaroncoffey :)

**Comment by jsspen** [comment]
New user here and I'm having the same issue...

Jellyfin log snippet
```
[2024-07-13 10:33:37.664 -04:00] [INF] "http://xxx.xxx.xx.112:8008/api/video/S9LZXheHddI/: Forbidden"
[2024-07-13 10:33:37.665 -04:00] [INF] "Getting metadata for video:  (S9LZXheHddI)"
[2024-07-13 10:33:37.665 -04:00] [INF] "Received metadata: null"
```

Container log snippet
```
2024-07-13T14:33:37.284547821Z [pid: 64|app: 0|req: 2635/2635] xxx.xxx.xx.112 () {32 vars in 449 bytes} [Sat Jul 13 10:33:37 2024] GET /api/video/bor_A0dSZDk/ => generated 59 bytes in 9 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
2024-07-13T14:33:37.333533558Z [pid: 64|app: 0|req: 2636/2636] xxx.xxx.xx.112 () {32 vars in 479 bytes} [Sat Jul 13 10:33:37 2024] GET /api/channel/UCsvn_Po0SmunchJYOWpOxMg/ => generated 59 bytes in 8 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
2024-07-13T14:33:37.341534340Z [pid: 64|app: 0|req: 2637/2637] xxx.xxx.xx.112 () {32 vars in 449 bytes} [Sat Jul 13 10:33:37 2024] GET /api/video/60BIq75BEAI/ => generated 59 bytes in 7 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
2024-07-13T14:33:37.350509650Z [pid: 64|app: 0|req: 2638/2638] xxx.xxx.xx.112 () {32 vars in 449 bytes} [Sat Jul 13 10:33:37 2024] GET /api/video/044JuOLrwRQ/ => generated 59 bytes in 8 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
2024-07-13T14:33:37.359537849Z [pid: 64|app: 0|req: 2639/2639] xxx.xxx.xx.112 () {32 vars in 479 bytes} [Sat Jul 13 10:33:37 2024] GET /api/channel/UCsvn_Po0SmunchJYOWpOxMg/ => generated 59 bytes in 6 msecs (HTTP/1.1 403) 8 headers in 270 bytes (1 switches on core 0)
```

Jellyfin is a bare metal install, v10.9.7
TubeArchivist is running in a docker container via Portainer on the same machine, v0.4.8
Metadata Plugin is v1.3.0.0
Exact URL in the plugin settings: `http://xxx.xxx.xx.112:8008/`
In the docker-compose: `TA_HOST=http://xxx.xxx.xx.112:8008/`

**Comment by boydthomson** [comment]
I'm getting episode titles and descriptions, but not Show Names or thumbnails.

[2024-07-13 08:32:07.560 -07:00] [DBG] AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2024-07-13 08:32:15.330 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:32:18.887 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:32:27.331 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:32:27.499 -07:00] [DBG] Timer stopped.
[2024-07-13 08:32:27.500 -07:00] [INF] "NEW! Clover the Lucky Cat - A St. Patrick's Day Kids Yoga Adventure" ("/mnt/tubar/youtube/UC5uIZ2KOZZeQDQo_Gsi_qbQ/XgoWxdK2avg.mp4") will be refreshed.
[2024-07-13 08:32:27.513 -07:00] [DBG] "OnLibraryManagerItemUpdated": Refreshing Item "NEW! Clover the Lucky Cat - A St. Patrick's Day Kids Yoga Adventure" [None, MetadataImport]
[2024-07-13 08:32:27.513 -07:00] [DBG] "Missing Episode Fetcher" not enabled for "NEW! Clover the Lucky Cat - A St. Patrick's Day Kids Yoga Adventure"
[2024-07-13 08:32:29.180 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:32:37.513 -07:00] [INF] Timer elapsed - processing queued items
[2024-07-13 08:32:37.513 -07:00] [INF] No events... stopping queue timer
[2024-07-13 08:32:39.331 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:32:49.158 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:32:51.330 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Music" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Cycling" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies.Agatha" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Christmas" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies.Anime" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows.Agatha" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows.Anime" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Yoga" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows-Cycling" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "YouTube" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Playlists" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "NEW! Clover the Lucky Cat - A St. Patrick's Day Kids Yoga Adventure" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "UC5uIZ2KOZZeQDQo Gsi qbQ" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "youtube" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "root" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Music" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Cycling" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies.Agatha" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Christmas" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Movies.Anime" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows.Agatha" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows.Anime" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Yoga" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Shows-Cycling" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "YouTube" has no parental rating set.
[2024-07-13 08:32:57.514 -07:00] [DBG] "Playlists" has no parental rating set.
[2024-07-13 08:32:59.187 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:33:01.512 -07:00] [DBG] New file refresher created for "/mnt/tubar/youtube/UC5uIZ2KOZZeQDQo_Gsi_qbQ/bxYE_hcMQq0.mp4"
[2024-07-13 08:33:03.331 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:33:15.331 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:33:19.093 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:33:27.331 -07:00] [DBG] Watching 2 WebSockets.
[2024-07-13 08:33:29.193 -07:00] [DBG] WS "192.168.1.35" received message: InboundWebSocketMessage`1 { Data: null, MessageType: KeepAlive, ServerId: null }
[2024-07-13 08:33:32.883 -07:00] [DBG] Resetting file refresher from "/mnt/tubar/youtube/UC5uIZ2KOZZeQDQo_Gsi_qbQ/bxYE_hcMQq0.mp4" to "/mnt/tubar/youtube/UC5uIZ2KOZZeQDQo_Gsi_qbQ"
[2024-07-13 08:33:39.331 -07:00] [DBG] Watching 2 WebSockets.

**Comment by jsspen** [comment]
Not sure how relevant this may be but if I test with curl as given in the TA docs, using the Jellyfin user, i.e. `sudo -u jellyfin curl -v http://xxx.xxx.xx.xxxx:8008/api/video/<video-id>/  -H "Authorization: Token xxxxxxxxxx"` it returns all the expected metadata. Could it be a problem with how the plugin is passing the token?

**Comment by DarkFighterLuke** [comment]
> Edit: So I added some extra logging to Plugin.cs and rebuilt the plugin, copied it over and restarted Jellyfin and... everything is working. Maybe a restart was all it really needed? No idea what happened but glad it's working!

Yeah, Jellyfin is a little bit messy on the plugins part and a lot of times problems get solved by just restarting...
