### ISSUE TITLE
[Bug]: Error  Couldn't parse ISO 8601 date string '2024-05-09 15:41:00'

### ISSUE THREAD

**Issue by danielnbalasoiu** [tubearchivist/tubearchivist-jf-plugin#23]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux (docker)

## Describe the bug

Plugin fails to install

Error:
```
o@https://jellyfin.local/web/main.jellyfin.bundle.js?b9b76074570af1132894:2:277631
31746/en/<@https://jellyfin.local/web/plugins-plugin.26a3687b6b29eef2d67e.chunk.js:1:9407
en@https://jellyfin.local/web/plugins-plugin.26a3687b6b29eef2d67e.chunk.js:1:9216
hu@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:60311
xi@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:119252
bs@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:108506
vs@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:108434
gs@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:108295
as@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:105130
is@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:105512
Bl@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:46687
76067/rs/<@https://jellyfin.local/web/node_modules.react-dom.bundle.js?b9b76074570af1132894:2:103087
```

Jellyfin version: `10.10.0` (`2024090905-amd64`)
TA version: `v0.4.10`

## Steps To Reproduce

Install TubeArchivist pluging following the [official docs](https://github.com/tubearchivist/tubearchivist-jf-plugin#from-official-repository-recommended). At step 4, Find TubeArchivistMetadata in the Metadata section and install it, the installation fails. 

## Expected behavior

TubeArchivist pluging is installed successfully.

### Relevant Jellyfin log output

```shell
No errors in Jellyfin (even after setting log level to debug mode).
```

### Anything else?

After manually installing it and restarting Jellyfin, I see the following error message:

```
[13:41:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeImageProvider
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeImageProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[13:41:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesImageProvider
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesImageProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[13:41:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[13:41:40] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

Another update: tried with Jellyfin `10.9.11` because if saw `10.9.1.0` [here](https://github.com/tubearchivist/tubearchivist-jf-plugin/compare/v1.3.2...master#diff-ffa5b716b5a57837f7929dfcca4b4dfdeb97210a7fd5a12d2f1978846d6f1743L13) and it works.

**Comment by danielnbalasoiu** [comment]
Update: Just tested today with the latest Jellyfin version: `2024091605-amd64` and I'm getting the same error message.

**Comment by danielnbalasoiu** [comment]
Update 2: 
I manuallly installed the plugin and after restarting Jellyfin, the following error is displayed:

```
[13:29:00] [ERR] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'MediaBrowser.Controller.Entities.UserItemData MediaBrowser.Controller.Library.IUserDataManager.GetUserData(System.Guid, MediaBrowser.Controller.Entities.BaseItem)'.
   at Jellyfin.Plugin.TubeArchivistMetadata.Tasks.JFToTubearchivistProgressSyncTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Jellyfin.Plugin.TubeArchivistMetadata.Tasks.JFToTubearchivistProgressSyncTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by DarkFighterLuke** [comment]
The plugin targets Jellyfin 10.9.x, any other version is not supported.
