### ISSUE TITLE
[Bug]: jellyfin 10.10.0 plugin malfunction

### ISSUE THREAD

**Issue by binarygeek119** [tubearchivist/tubearchivist-jf-plugin#24]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

linux

### Your Bug Report

the plugin doesn't load on 10.10.0 needs updating.

### Relevant Jellyfin log output

```shell
[2024-10-14 00:18:11.501 -05:00] [INF] [286] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.TubeArchivistMetadata, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/tubearchivist_1.3.2/Jellyfin.Plugin.TubeArchivistMetadata.dll"

[2024-10-14 00:37:35.771 -05:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating "Jellyfin.Plugin.TubeArchivistMetadata.Plugin"
System.MissingMethodException: Method not found: 'MediaBrowser.Model.Tasks.IScheduledTaskWorker[] MediaBrowser.Model.Tasks.ITaskManager.get_ScheduledTasks()'.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
[2024-10-14 00:37:35.807 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Plugin "/config/plugins/tubearchivist_1.3.2" has been disabled.
[2024-10-14 00:37:35.809 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TVHeadend" "11.2405.5.0"
[2024-10-14 00:37:35.812 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TVmaze" "11.2403.5.0"
[2024-10-14 00:37:35.814 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Webhook" "15.2410.9.0"
[2024-10-14 00:37:35.819 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "YoutubeMetadata" "1.0.3.12"
[2024-10-14 00:37:35.820 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.10.0.0"
[2024-10-14 00:37:35.820 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.10.0.0"
[2024-10-14 00:37:35.820 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.10.0.0"
[2024-10-14 00:37:35.893 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.10.0.0"
[2024-10-14 00:37:35.894 -05:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.10.0.0"
[2024-10-14 00:37:36.020 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeImageProvider"
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeImageProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2024-10-14 00:37:36.022 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesImageProvider"
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesImageProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2024-10-14 00:37:36.099 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider"
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.EpisodeMetadataProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2024-10-14 00:37:36.099 -05:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider"
System.Data.DataException: Uninitialized plugin!
   at Jellyfin.Plugin.TubeArchivistMetadata.Providers.SeriesMetadataProvider..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by DarkFighterLuke** [comment]
Have you tried to restart the Jellyfin server?

**Comment by binarygeek119** [comment]
yes

**Comment by DarkFighterLuke** [comment]
I am using it with Jellyfin 10.9.11 and I can't reproduce this bug.

**Comment by binarygeek119** [comment]
im on jellyfin 10.10.0 unstable

**Comment by DarkFighterLuke** [comment]
Sorry, I mislead the version! The plugin only supports latest stable version, so 10.10.x is not currently supported.

**Comment by NetDude12** [comment]
I know  we are roughly 10hours into 10.10.0 being stable, any plans to support 10.10.x in the future?

**Comment by DarkFighterLuke** [comment]
@binarygeek119 now the plugin supports Jellyfin 10.10
