### ISSUE TITLE
[Bug]: Crashing during playing of Live TV

### ISSUE THREAD

**Issue by bashman83** [tubearchivist/tubearchivist-jf-plugin#29]
### I've read the documentation

- [X] I'm running the latest version of tubearchivist-jf-plugin.
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology Linux & Docker

### Relevant Jellyfin log output

```shell
[2024-11-20 13:57:21.371 +13:00] [INF] [35] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/var/packages/ffmpeg7/target/bin/ffmpeg" "-analyzeduration 3000000 -probesize 1G  -i \"http://localhost:9981/stream/channelid/299055571?ticket=6f698787678b00295ad8fbfbeefbcb8d0d79772b\" -map_metadata -1 -map_chapters -1 -threads 0 -sn -codec:v:0 libx264 -preset superfast -crf 23 -maxrate 66419477 -bufsize 132838954 -profile:v:0 high -level 51 -x264opts:0 subme=0:me_range=16:rc_lookahead=10:me=hex:open_gop=0 -force_key_frames:0 \"expr:gte(t,n_forced*3)\" -sc_threshold:v:0 0 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,yadif=0:-1:0,format=yuv420p\" -codec:a:0 libfdk_aac -ab 384000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"768b5a1f7286eade0593833f30c1303f-1.mp4\" -start_number 0 -hls_base_url \"hls/768b5a1f7286eade0593833f30c1303f/\" -hls_segment_filename \"/volume1/@appdata/jellyfin/cache/transcodes/768b5a1f7286eade0593833f30c1303f%d.mp4\" -hls_playlist_type event -hls_list_size 0 -y \"/volume1/@appdata/jellyfin/cache/transcodes/768b5a1f7286eade0593833f30c1303f.m3u8\""
[2024-11-20 13:57:32.480 +13:00] [FTL] [35] Main: Unhandled Exception
System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Jellyfin.Plugin.TubeArchivistMetadata.Plugin.OnPlaybackProgress(Object sender, PlaybackProgressEventArgs eventArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[2024-11-20 13:57:32.482 +13:00] [FTL] [27] Main: Unhandled Exception
System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Jellyfin.Plugin.TubeArchivistMetadata.Plugin.OnPlaybackProgress(Object sender, PlaybackProgressEventArgs eventArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by joshand** [comment]
I observed the same issue. However, I was able to stop the crash from happening when I disabled all of the Playback synchronization options. I'm guessing it was specifically "Synchronize Jellyfin playback progress to TubeArchivist", but I've not tested individually. Perhaps Jellyfin is trying to send progress of a Live TV session back to TA?

**Comment by DarkFighterLuke** [comment]
Hi @bashman83 , can you provide me a live tv to use for example in order to test this behavior?

**Comment by bashman83** [comment]
Hi?@DarkFighterLuke I was using the TVHeadend plugin when this error occurred.
So this has some local Digital TV broadcasts, as well as some IPTV channels provided by @matthuisman

**Comment by DarkFighterLuke** [comment]
Moreover, what are your Jellyfin and TubeArchivist plugin versions?

**Comment by bashman83** [comment]
Both Jellyfin & TA-JF are at the newest versions available. So 10.10.3 & 1.3.4.0
As mentioned above, this is only an issue when using the playback synchronisation. When that isn't ticked it all works perfectly fine.

**Comment by Jurrer** [comment]
I'm not sure if it will help but from the logs I noticed this plugin tries to synchronize to -> TA every played video.
For example, while watching Anime from a different library it's sending requests to sync the watching status to TA 
Of course it is returning an error saying that the video cannot be found. It's harmless in this case but maybe it's related

**Comment by DarkFighterLuke** [comment]
@Jurrer you're right, I've already find out the reason, but unfortunately I have no time to fix it quickly at the moment. Maybe in some days I will release a fix.

**Comment by bashman83** [comment]
> I think that this bug has been fixed, can you confirm that?

I'm still getting this error during Live TV. Although I haven't used it as much as I did previously. However, when I watch music videos or when I have other home videos, in Jellyfin, they also crash JF during playback. I will try to track down the error in the long in the next day or two, but from memory it all looked exactly the same.

**Comment by ngthunter** [comment]
Same for me, JF crashes whenever I watch a movie as long as sync to TA is on

**Comment by fernandeusto** [comment]
Hi, I just wanted to confirm that I'm also experiencing this issue.

Whenever I play any media from a library **other than TubeArchivist**, Jellyfin crashes with the following error:

```
[22:25:14] [INF] [25] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for Fernando. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[22:25:15] [FTL] [26] Main: Unhandled Exception
System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Jellyfin.Plugin.TubeArchivistMetadata.Plugin.OnPlaybackProgress(Object sender, PlaybackProgressEventArgs eventArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.ArgumentException: Guid can't be empty (Parameter 'id')
   at Emby.Server.Implementations.Library.LibraryManager.GetItemById(Guid id)
   at Jellyfin.Plugin.TubeArchivistMetadata.Plugin.OnPlaybackProgress(Object sender, PlaybackProgressEventArgs eventArgs)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Container stopped
```

It seems like the plugin is trying to handle playback progress for **all media**, even when it's not related to TubeArchivist, and crashes when the item doesn't have a valid GUID.

And only "Synchronize Jellyfin playback progress to TubeArchivist" have checked.

Disabling playback sync avoids the crash, but that defeats the purpose of having the plugin installed. I hope this can be addressed soon—maybe by filtering playback events to only process TubeArchivist items?

Thanks for your work!
